import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync } from 'node:fs';
import { sassPlugin } from 'esbuild-sass-plugin';
import { copy } from "esbuild-plugin-copy";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Virtual module plugin: inlines epub.min.js as a string constant
// Used by epub.ts to build the iframe srcdoc with epubjs embedded
const epubJsVirtualPlugin = {
  name: 'epubjs-virtual',
  setup(build) {
    build.onResolve({ filter: /^virtual:epubjs-source$/ }, args => ({
      path: 'virtual:epubjs-source',
      namespace: 'epubjs-virtual',
    }));
    build.onLoad({ filter: /.*/, namespace: 'epubjs-virtual' }, () => {
      const epubJsPath = new URL('node_modules/epubjs/dist/epub.min.js', import.meta.url).pathname;
      const source = readFileSync(epubJsPath, 'utf-8');
      return {
        contents: `const epubJsSource = ${JSON.stringify(source)};\nexport default epubJsSource;`,
        loader: 'js',
      };
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: [{ in: "src/main.ts", out: "main" }, "src/styles.scss"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "epubjs",
    ...builtinModules
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  plugins: [
    epubJsVirtualPlugin,
    sassPlugin({}),
    copy({
      resolveFrom: "cwd",
      watch: !prod,
      assets: [
        { from: "manifest.json", to: "dist/manifest.json" },
        { from: "node_modules/pdfjs-dist/legacy/build/pdf.min.js", to: "dist/pdf.worker.js" },
      ],
    }),
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
